--- #YAML:1.0
name:               Net-IP-Match-Bin
version:            0.03
abstract:           Perl extension for match IP addresses against Net ranges
author:
    - Tomo <tomo_at_c-wind.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
